ReportesWeb1_2/Controllers/ReportesController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using Oracle.ManagedDataAccess.Client;
using ReportesWeb1_2.ModelsReportes;
using ReportesWeb1_2.ModelsSQLServer;
using ReportesWeb1_2.Services;
using ReportesWeb1_2.ServicesReportes;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ReportesWeb1_2.Controllers
{
    [Authorize]
    public class ReportesController : Controller
    {
        private ProsisSQLServerModel db = new ProsisSQLServerModel();
        private MetodosGlbRepository MtGlb = new MetodosGlbRepository();
        private Validation validaciones = new Validation();
        private CajeroReceptorRepository CaReRepository = new CajeroReceptorRepository();
        private TurnoCarrilesRepository TuCaRepository = new TurnoCarrilesRepository();
        private DiaCasetaRepository DiCaRepository = new DiaCasetaRepository();

        static string NameConnectionString = string.Empty;
        static string DelegacionBag = string.Empty;
        static string PlazaBag = string.Empty;
        static string IdPlaza = string.Empty;
        static string IdDelegacion = string.Empty;
        static string NomPlaza = string.Empty;

        private async Task UserPlaza()
        {
            await Task.Run(() =>
            {
                var userMatricula = User.Identity.Name.Substring(0, User.Identity.Name.LastIndexOf('@'));

                var Result = db.Type_Delegacion
                                .GroupJoin(
                                    db.Type_Plaza,
                                    del => del.Id_Delegacion,
                                    pla => pla.Delegacion_Id,
                                    (del, pla) => new { del, pla })
                                .SelectMany(del => del.pla.DefaultIfEmpty(), (del, pla) => new { del.del, pla })
                                .Join(
                                    db.Type_Operadores,
                                    pla => pla.pla.Id_Plaza,
                                    ope => ope.Plaza_Id,
                                    (pla, ope) => new { pla, ope })
                                .Where(x => x.ope.Num_Capufe == userMatricula).FirstOrDefault();

                NameConnectionString = "Oracle" + Result.pla.pla.Num_Plaza;
                DelegacionBag = Result.pla.del.Nom_Delegacion;
                IdDelegacion = Result.pla.del.Num_Delegacion;
                PlazaBag = Result.pla.pla.Num_Plaza + " " + Result.pla.pla.Nom_Plaza;
                IdPlaza = Result.pla.pla.Num_Plaza;
                NomPlaza = Result.pla.pla.Nom_Plaza;
            });
        }

        // GET: Reportes
        public ActionResult Index()
        {
            return View();
        }

        // GET: Cajero - Receptor Form
        [HttpGet]
        public async Task<ActionResult> CajeroReceptorIndex()
        {
            await UserPlaza();
            var model = new CajeroReceptorModel()
            {
                ListBolsas = new List<Bolsas>(),
            };

            ViewBag.Delegacion = DelegacionBag;

            string aux = "";

            if (PlazaBag.Contains("08"))
            {
                aux = "001" + " " + NomPlaza;
                ViewBag.Plaza = aux;
            }
            else
            {
                ViewBag.Plaza = PlazaBag;
            }

            return View(model);
        }

        //POST: Cajero - Receptor Form
        [HttpPost]
        public ActionResult CajeroReceptorIndex(CajeroReceptorModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string errorCentavos = "";
                    string errorComentarios = "";
                    string errorDiferenciaSegundos = "";
                    bool errorValidacion = true;
                    var table = new DataTable("FIN_POSTE");
                    string Query = $"SELECT * FROM FIN_POSTE WHERE MATRICULE = '{model.NumCajeroReceptor}'"; //Query para traer datos si existe el cajero
                    bool validation;

                    OracleCommand Command = new OracleCommand(Query, MtGlb.GetConnectionOracle(NameConnectionString));

                    using (OracleDataAdapter adapter = new OracleDataAdapter(Command))
                    {
                        adapter.Fill(table);

                        if (table.Rows.Count >= 1)
                        {
                            validation = true;
                        }
                        else
                        {
                            validation = false;
                        }
                    }

                    if (validation == true)
                    {
                        var Delegaciones = new JavaScriptSerializer().Serialize(GetDelegaciones().Data);
                        model.ListDelegaciones = JsonConvert.DeserializeObject<List<SelectListItem>>(Delegaciones);

                        var Plazas = new JavaScriptSerializer().Serialize(GetPlazas().Data);
                        model.ListPlazas = JsonConvert.DeserializeObject<List<SelectListItem>>(Plazas);

                        var Turnos = new JavaScriptSerializer().Serialize(GetTurnos().Data);
                        model.ListTurnos = JsonConvert.DeserializeObject<List<SelectListItem>>(Turnos);

                        var Administradores = new JavaScriptSerializer().Serialize(GetAdministradores().Data);
                        model.ListAdministradores = JsonConvert.DeserializeObject<List<SelectListItem>>(Administradores);

                        var Delegacion = model.ListDelegaciones.Find(x => x.Value == IdDelegacion);
                        var Plaza = model.ListPlazas.Find(x => x.Value == IdPlaza);
                        var Turno = model.ListTurnos.Find(x => x.Value == model.IdTurno);
                        var Administrador = model.ListAdministradores.Find(x => x.Value == model.IdAdministrador);
                        string admin_num = "";
                        string Matricule_Cajero = Administrador.Value;
                        var Query_Cajero = db.Type_Operadores.Where(x => x.Num_Gea == Matricule_Cajero).FirstOrDefault();

                        if (Query_Cajero != null)
                            admin_num = Query_Cajero.Num_Capufe;
                        else
                            admin_num = Administrador.Value;

                        List<Bolsas> listaBolsas = new List<Bolsas>();
                        List<Bolsas> lista = new List<Bolsas>();

                        listaBolsas = CaReRepository._PartialViewBolsas(model.Fecha, Plaza.Value, Turno.Text, model.NumCajeroReceptor, Delegacion.Text, admin_num + "    " + Administrador.Text, NameConnectionString);

                        if (listaBolsas.Count != 0)
                        {
                            foreach (var item in listaBolsas)
                            {
                                //Query para obtener el saldo total de la bolsa
                                string StrQuerys = "SELECT MATRICULE,SAC AS Expr1, NVL(NB_POSTE, 0) + NVL(NB_POSTE_POS, 0) AS Expr2, NVL(RED_RCT_MONNAIE1, 0) AS Expr3, " +
                                    "NVL(RED_RCT_CHQ, 0) AS Expr4, NVL(RED_NB_CHQ, 0) AS Expr5, NVL(RED_RCT_DEVISE, 0) AS Expr6, NVL(RED_RCT_MONNAIE3, 0) AS Expr7, " +
                                    "NVL(RED_RCT_MONNAIE4, 0) AS Expr8, NVL(RED_CPT1, 0) AS Expr9, NVL(RED_RCT_MONNAIE1, 0) + NVL(RED_RCT_MONNAIE2, 0) + NVL(RED_RCT_MONNAIE3, 0) " +
                                    "+ NVL(RED_RCT_MONNAIE4, 0) + NVL(RED_RCT_CHQ, 0) + NVL(RED_RCT_DEVISE, 0) AS Expr10, NVL(POSTE_RCT_MONNAIE1, 0) + NVL(POSTE_RCT_MONNAIE2, 0) " +
                                    "+ NVL(POSTE_RCT_MONNAIE3, 0) + NVL(POSTE_RCT_MONNAIE4, 0) + NVL(POSTE_RCT_DEVISE, 0) + NVL(POSTE_RCT_CHQ, 0) + NVL(POSTE_POS_RCT_MONNAIE1, " +
                                    "0) + NVL(POSTE_POS_RMB_MONNAIE1, 0) + NVL(POSTE_POS_RCT_MONNAIE2, 0) + NVL(POSTE_POS_RCT_MONNAIE3, 0) + NVL(POSTE_POS_RCT_MONNAIE4, 0) " +
                                    "+ NVL(POSTE_POS_RCT_DEVISE, 0) + NVL(POSTE_POS_RCT_CHQ, 0) AS Expr11, NVL(RED_RCT_MONNAIE1, 0) + NVL(RED_RCT_MONNAIE2, 0) " +
                                    "+ NVL(RED_RCT_MONNAIE3, 0) + NVL(RED_RCT_MONNAIE4, 0) + NVL(RED_RCT_DEVISE, 0) + NVL(RED_RCT_CHQ, 0) - NVL(POSTE_RCT_MONNAIE1, 0) " +
                                    "- NVL(POSTE_RCT_MONNAIE2, 0) - NVL(POSTE_RCT_MONNAIE3, 0) - NVL(POSTE_RCT_MONNAIE4, 0) - NVL(POSTE_RCT_DEVISE, 0) - NVL(POSTE_RCT_CHQ, 0) " +
                                    "- NVL(POSTE_POS_RCT_MONNAIE1, 0) - NVL(POSTE_POS_RMB_MONNAIE1, 0) - NVL(POSTE_POS_RCT_MONNAIE2, 0) - NVL(POSTE_POS_RCT_MONNAIE3, 0) " +
                                    "- NVL(POSTE_POS_RCT_MONNAIE4, 0) - NVL(POSTE_POS_RCT_DEVISE, 0) - NVL(POSTE_POS_RCT_CHQ, 0) AS Expr12, NVL(RED_RCT_MONNAIE1, 0) " +
                                    "- NVL(POSTE_RCT_MONNAIE1, 0) - NVL(POSTE_POS_RMB_MONNAIE1, 0) - NVL(POSTE_POS_RCT_MONNAIE1, 0) AS Expr13, NVL(RED_RCT_CHQ, 0) " +
                                    "- NVL(POSTE_RCT_CHQ, 0) - NVL(POSTE_POS_RCT_CHQ, 0) AS Expr14, NVL(RED_RCT_DEVISE, 0) - NVL(POSTE_RCT_DEVISE, 0) - NVL(POSTE_POS_RCT_DEVISE, 0) " +
                                    "AS Expr15, NVL(RED_CPT24, 0) AS Expr16, NVL(RED_CPT25, 0) AS Expr17, NVL(RED_JETON, 0) - NVL(POSTE_JETON, 0) AS Expr18, NVL(RED_RDD, 0) " +
                                    "- NVL(POSTE_RDD, 0) AS Expr19, NVL(RED_GRATUIT, 0) + NVL(RED_CPT2, 0) - NVL(POSTE_GRATUIT, 0) AS Expr20, MATRICULE_COMMENTAIRE, COMMENTAIRE, " +
                                    "0 AS Expr21, TO_CHAR(DATE_REDDITION, 'YYYYMMDDHH24MISS') AS Expr22, ID_SITE, RED_CPT21, NB_POSTE, ETAT_REDDITION, " +

ReportesWeb1_2/Views/Reportes/CajeroReceptorIndex.cshtml
@model ReportesWeb1_2.ModelsReportes.CajeroReceptorModel

@{
    ViewBag.Title = "Cajero - Receptor";
}

@section Scripts {

    <script>
        $(document).ready(function () {
            LoadTurnos();
            LoadAdministradores();
            OutLoader();
        });

         function LoadTurnos() {
            $.ajax({
                url: '@Url.Action("GetTurnos", "Reportes")',
                type: "GET",
                data: "{}",
                cache: false,
                success: function (data) {
                    $.each(data, function (i, row) {
                        var $option = $('<option>');
                        $option.val(row.Value);
                        $option.html(row.Text);
                        $('#IdTurno').append($option);
                    });
                },
                error: function (ex) {
                    alert('Error!!!' + ex);
                },
            });
        }

        function LoadAdministradores() {
            $.ajax({
                url: '@Url.Action("GetAdministradores", "Reportes")',
                type: 'GET',
                data: '{}',
                cache: false,
                success: function (data) {
                    $.each(data, function (i, row) {
                        var $option = $('<option>');
                        $option.val(row.Value);
                        $option.html(row.Text);
                        $('#IdAdministrador').append($option);
                    });
                },
                error: function (ex) {
                    alert("Error!!!" + ex);
                }
            });
        }

    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

@*<div id="loader-wrapper">
        <div id="loader"></div>
    </div>*@

<div class="container">
    <h1>Cajero-Receptor</h1>
</div>
<hr />

@using (Ajax.BeginForm("CajeroReceptorIndex", "Reportes", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "divListaBolsas" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.IdDelegacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.LabelFor(model => model.IdDelegacion, (string)ViewBag.Delegacion, htmlAttributes: new { @class = "font-weight-bold" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdPlaza, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.LabelFor(model => model.IdPlaza, (string)ViewBag.Plaza, htmlAttributes: new { @class = "font-weight-bold" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumCajeroReceptor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.NumCajeroReceptor, new { htmlAttributes = new { @class = "form-control textbox2 contorno", placeholder = "Numero de Cajero" } })
                @Html.ValidationMessageFor(model => model.NumCajeroReceptor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTurno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.IdTurno, new SelectList(string.Empty, "Value", "Text"), htmlAttributes: new { @class = "custom-select dropdown3 contorno", size = "3" })
                @Html.ValidationMessageFor(model => model.IdTurno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdAdministrador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.IdAdministrador, new SelectList(string.Empty, "Value", "Text"), "Seleccione un administrador", htmlAttributes: new { @class = "custom-select contorno" })
                @Html.ValidationMessageFor(model => model.IdAdministrador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Fecha)
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-4 col-md-6">
                <input type="submit" value="Generar Reportes" class="btn btn-primary boton2" />
            </div>
        </div>
    </div>
}

<div id="divListaBolsas" class="row">
    @Html.Partial("_ListaBolsasPartial", Model)
</div>

ReportesWeb1_2/Views/Reportes/DiaCasetaIndex.cshtml
@model ReportesWeb1_2.ModelsReportes.DiaCasetaModel

@{
    ViewBag.Title = "Dia-Caseta";
}

@section Scripts{

    <script>
        $(document).ready(function () {
            LoadEncargadoTurno();
            LoadAdministradores();
            OutLoader();

            $('#loaderButton').on('click', function (e) {
                if ($('#form0').valid()) {
                    /*Al terminar de cargar el sitio, primero se va la animación del Preloader*/
                    $("#loader").fadeIn();
                    /*Medio segundo despues, se va poco a poco el fondo del preloader*/
                    $("#loader-wrapper").delay(500).fadeIn("slow");

                    $('#form0').submit();
                }
            });
        });

        function LoadEncargadoTurno() {
            $.ajax({
                url: '@Url.Action("GetEncargadosTurno", "Reportes")',
                type: 'GET',
                data: '{}',
                cache: false,
                success: function (data) {
                    $.each(data, function (i, row) {
                        var $option = $('<option>');
                        $option.val(row.Value);
                        $option.html(row.Text);
                        $('#IdEncargadoTurno').append($option);
                    });
                },
                error: function (ex) {
                    alert('Error!!!' + ex);
                },
            });
        }


        function LoadAdministradores() {
            $.ajax({
                url: '@Url.Action("GetAdministradores", "Reportes")',
                type: 'GET',
                data: '{}',
                cache: false,
                success: function (data) {
                    $.each(data, function (i, row) {
                        var $option = $('<option>');
                        $option.val(row.Value);
                        $option.html(row.Text);
                        $('#IdAdministrador').append($option);
                    });
                },
                error: function (ex) {
                    alert("Error!!!" + ex);
                }
            });
        }

    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

<div id="loader-wrapper">
    <div id="loader"></div>
</div>

<div class="container">
    <h1>Dia-Caseta</h1>
</div>

@using (Html.BeginForm("ReportDiaCasetaView", "Reportes", FormMethod.Post, htmlAttributes: new { @id = "form0" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdDelegacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.LabelFor(model => model.IdDelegacion, (string)ViewBag.Delegacion, htmlAttributes: new { @class = "font-weight-bold" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdPlaza, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.LabelFor(model => model.IdPlaza, (string)ViewBag.Plaza, htmlAttributes: new { @class = "font-weight-bold" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdEncargadoTurno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.IdEncargadoTurno, new SelectList(string.Empty, "Value", "Text"), "Seleccione un encargado de turno", htmlAttributes: new { @class = "form-control contorno" })
                @Html.ValidationMessageFor(model => model.IdEncargadoTurno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdAdministrador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.IdAdministrador, new SelectList(string.Empty, "Value", "Text"), "Seleccione un administrador", htmlAttributes: new { @class = "form-control contorno" })
                @Html.ValidationMessageFor(model => model.IdAdministrador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Fecha)
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextAreaFor(model => model.Observaciones, new { @class = "form-control contorno", @rows = 3 })
                @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="button" value="Generar reportes" class="btn btn-primary boton2" id="loaderButton" />
            </div>
        </div>
    </div>
}

ReportesWeb1_2/Views/Reportes/TurnoCarrilesIndex.cshtml
@model ReportesWeb1_2.ModelsReportes.TurnoCarrilesModel

@{
    ViewBag.Title = "Turno-Carriles";
}

@section Scripts{

    <script>
        $(document).ready(function () {
            LoadTurnos();
            LoadEncargadoTurno();
            LoadAdministradores();
            OutLoader();

            $('#loaderButton').on('click', function (e) {
                if ($('#form0').valid()) {
                    /*Al terminar de cargar el sitio, primero se va la animación del Preloader*/
                    $("#loader").fadeIn();
                    /*Medio segundo despues, se va poco a poco el fondo del preloader*/
                    $("#loader-wrapper").delay(500).fadeIn("slow");

                    $('#form0').submit();
                }
            });
        });

         function LoadTurnos() {
            $.ajax({
                url: '@Url.Action("GetTurnos", "Reportes")',
                type: "GET",
                data: "{}",
                cache: false,
                success: function (data) {
                    $.each(data, function (i, row) {
                        var $option = $('<option>');
                        $option.val(row.Value);
                        $option.html(row.Text);
                        $('#IdTurno').append($option);
                    });
                },
                error: function (ex) {
                    alert('Error!!!' + ex);
                },
            });
        }

        function LoadEncargadoTurno() {
            $.ajax({
                url: '@Url.Action("GetEncargadosTurno", "Reportes")',
                type: 'GET',
                data: '{}',
                cache: false,
                success: function (data) {
                    $.each(data, function (i, row) {
                        var $option = $('<option>');
                        $option.val(row.Value);
                        $option.html(row.Text);
                        $('#IdEncargadoTurno').append($option);
                    });
                },
                error: function (ex) {
                    alert('Error!!!' + ex);
                },
            });
        }


        function LoadAdministradores() {
            $.ajax({
                url: '@Url.Action("GetAdministradores", "Reportes")',
                type: 'GET',
                data: '{}',
                cache: false,
                success: function (data) {
                    $.each(data, function (i, row) {
                        var $option = $('<option>');
                        $option.val(row.Value);
                        $option.html(row.Text);
                        $('#IdAdministrador').append($option);
                    });
                },
                error: function (ex) {
                    alert("Error!!!" + ex);
                }
            });
        }

    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

<div id="loader-wrapper">
    <div id="loader"></div>
</div>

<div class="container">
    <h1>Turno-Carriles</h1>

    @if (ViewData["Error"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            @ViewData["Error"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
</div>
@using (Html.BeginForm("ReportTurnoCarrilesView", "Reportes", FormMethod.Post, htmlAttributes: new { @id = "form0" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdDelegacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.LabelFor(model => model.IdDelegacion, (string)ViewBag.Delegacion, htmlAttributes: new { @class = "font-weight-bold" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdPlaza, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.LabelFor(model => model.IdPlaza, (string)ViewBag.Plaza, htmlAttributes: new { @class = "font-weight-bold" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTurno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.IdTurno, new SelectList(string.Empty, "Value", "Text"), htmlAttributes: new { @class = "custom-select dropdown3 contorno", size = "3" })
                @Html.ValidationMessageFor(model => model.IdTurno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdEncargadoTurno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.IdEncargadoTurno, new SelectList(string.Empty, "Value", "Text"), "Seleccione un encargado de turno", htmlAttributes: new { @class = "form-control contorno" })
                @Html.ValidationMessageFor(model => model.IdEncargadoTurno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdAdministrador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.IdAdministrador, new SelectList(string.Empty, "Value", "Text"), "Seleccione un administrador", htmlAttributes: new { @class = "form-control contorno" })
                @Html.ValidationMessageFor(model => model.IdAdministrador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Fecha)
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextAreaFor(model => model.Observaciones, new { @class = "form-control contorno", @rows = 3 })
                @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="button" value="Generar reportes" class="btn btn-primary boton2" id="loaderButton" role="button" />
            </div>
        </div>
    </div>
}

ReportesWeb1_2/Views/Reportes/_ListaBolsasPartial.cshtml
@model ReportesWeb1_2.ModelsReportes.CajeroReceptorModel

@if (Model.ListBolsas != null && Model.ListBolsas.Any())
{
    <div class="col-lg-12">
        <p class="text-center lead">LISTA DE BOLSAS</p>
        <table class="table table-striped" id="mytable">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Inicio</th>
                    <th scope="col">Fin</th>
                    <th scope="col">Carril</th>
                    <th scope="col">Bolsa</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ListBolsas)
                {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td>@item.Inicio</td>
                        <td>@item.Fin</td>
                        <td>@item.Carril</td>
                        <td>@item.Bolsa</td>
                        <td><a class="btn btn-primary" href="@Url.Action("ReportCajeroReceptorView", "Reportes", new { IdRow = item.Id})" target="_blank" @*onclick="InLoaderVal()"*@ id="loaderButton" role="button">Generar</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="col-lg-12">
        @if (ViewBag.Nulo == "rojo")
        {
            <p class="text-center lead bg-danger text-white">NO HAY DATOS</p>
        }
        else
        {
            <p class="text-center lead">NO HAY DATOS</p>
        }
    </div>
}
@if (ViewBag.Error != null && ViewBag.Error != "")
{
    <div class="alert alert-danger col-md-12 text-center" role="alert">
        @ViewBag.Error
    </div>
}
@if (ViewBag.ErrorCentavos != null && ViewBag.ErrorCentavos != "")
{
    <div class="alert alert-danger col-md-12 text-center" role="alert">
        @ViewBag.ErrorCentavos
    </div>
}
@if (ViewBag.ErrorComentarios != null && ViewBag.ErrorComentarios != "")
{
    <div class="alert alert-danger col-md-12 text-center" role="alert">
        @ViewBag.ErrorComentarios
    </div>
}
@if (ViewBag.errorDiferenciaSegundos != null && ViewBag.errorDiferenciaSegundos != "")
{
    <div class="alert alert-danger col-md-12 text-center" role="alert">
        @ViewBag.errorDiferenciaSegundos
    </div>
}